// build.ts generates src/tui/banner.ts and src/version.ts then compiles the binary

import { statSync } from 'node:fs';
import { join } from 'node:path';
import { PROTOCOL } from '../lib/src/protocol.ts';

async function bundleBanner(src: string, out: string): Promise<void> {
	process.stdout.write('Bundling banner...\n');
	const text = await Bun.file(src).text();
	await Bun.write(out,
		`// AUTO-GENERATED by build.ts. Do not edit.\nexport const BANNER = ${JSON.stringify(text)};\n`,
	);
	process.stdout.write(`  → ${out}\n`);
}

// Bake the version facts in at build time so `--version` is a constant print
// with no runtime package.json read. VERSION comes from the project root
// package.json; PROTOCOL_HEX is the wire version the lib already renders.
async function bundleVersion(out: string): Promise<void> {
	process.stdout.write('Bundling version...\n');
	const pkg = await Bun.file(join(import.meta.dir, '..', 'package.json')).json();
	await Bun.write(out,
		'// AUTO-GENERATED by build.ts. Do not edit.\n' +
		`export const VERSION = ${JSON.stringify(pkg.version)};\n` +
		`export const PROTOCOL_HEX = ${JSON.stringify(PROTOCOL.protocolVersionHex)};\n`,
	);
	process.stdout.write(`  → ${out}\n`);
}

await bundleBanner('src/ascii', 'src/tui/banner.ts');
await bundleVersion('src/version.ts');

if (process.argv.includes('--compile')) {
	const outfile = process.platform === 'win32'
		? './dist/covcom.exe'
		: './dist/covcom';
	process.stdout.write('Building binary...\n');
	const result = await Bun.build({
		entrypoints: ['src/main.ts'],
		compile: { outfile },
	});
	if (!result.success) {
		process.stderr.write('Build failed:\n');
		for (const msg of result.logs) process.stderr.write(`  ${msg.message}\n`);
		process.exit(1);
	}
	const size = statSync(outfile).size;
	process.stdout.write(`Built: ${outfile}  (${(size / 1024).toFixed(1)} KB)\n`);
}
