// build.ts generates src/tui/banner.ts then compiles the binary

import { statSync } from 'node:fs';

async function bundleBanner(src: string, out: string): Promise<void> {
	process.stdout.write('Bundling banner...\n');
	const text = await Bun.file(src).text();
	await Bun.write(out,
		`// AUTO-GENERATED by build.ts. Do not edit.\nexport const BANNER = ${JSON.stringify(text)};\n`,
	);
	process.stdout.write(`  → ${out}\n`);
}

await bundleBanner('../docs/ascii', 'src/tui/banner.ts');

if (process.argv.includes('--compile')) {
	const outfile = process.platform === 'win32'
		? './dist/covcom.exe'
		: './dist/covcom';
	process.stdout.write('Building binary...\n');
	const result = await Bun.build({
		entrypoints: ['src/main.ts'],
		compile: { outfile },
	});
	if (!result.success) {
		process.stderr.write('Build failed:\n');
		for (const msg of result.logs) process.stderr.write(`  ${msg.message}\n`);
		process.exit(1);
	}
	const size = statSync(outfile).size;
	process.stdout.write(`Built: ${outfile}  (${(size / 1024).toFixed(1)} KB)\n`);
}
