// build.ts — generates src/chacha/worker-bundle.ts then compiles the binary

import { statSync } from 'node:fs'

async function bundleWorker(entry: string, out: string, label: string): Promise<void> {
	process.stdout.write(`Bundling ${label} worker...\n`)
	const build = await Bun.build({
		entrypoints: [entry],
		target: 'browser',
		format: 'iife',
		minify: true,
	})
	if (!build.success) {
		process.stderr.write(`${label} worker build failed:\n`)
		for (const msg of build.logs) process.stderr.write(`  ${msg.message}\n`)
		process.exit(1)
	}
	const js = await build.outputs[0].text()
	await Bun.write(out,
		`// AUTO-GENERATED by build.ts — do not edit\nexport const WORKER_BUNDLE = ${JSON.stringify(js)};\n`,
	)
	process.stdout.write(`  → ${out}\n`)
}

await bundleWorker(
	'node_modules/leviathan-crypto/dist/chacha20/pool-worker.js',
	'src/chacha/worker-bundle.ts',
	'ChaCha20',
)

if (process.argv.includes('--compile')) {
	const outfile = process.platform === 'win32'
		? './dist/lvthn-messenger.exe'
		: './dist/lvthn-messenger'
	process.stdout.write('Building binary...\n')
	const result = await Bun.build({
		entrypoints: ['src/main.ts'],
		compile: { outfile },
	})
	if (!result.success) {
		process.stderr.write('Build failed:\n')
		for (const msg of result.logs) process.stderr.write(`  ${msg.message}\n`)
		process.exit(1)
	}
	const size = statSync(outfile).size
	process.stdout.write(`Built: ${outfile}  (${(size / 1024).toFixed(1)} KB)\n`)
}
