/**
 * npm.ts - npm staging for the covcom meta and platform packages.
 *
 * stageNpm() writes publish-ready package trees under dist/npm/ at the repo
 * root. Everything is generated here: manifests, the launcher shim, READMEs.
 * Nothing under dist/npm/ is committed, and no tree package.json carries a
 * publishable name, so `npm publish` anywhere in the workspace publishes
 * nothing. Every staged dir (meta and platform alike) is removed before it
 * is regenerated, so staging is clean by construction; the other app's
 * staging under dist/npm/ is never touched.
 *
 * Layout per app (meta package plus one platform package per target):
 *
 *   dist/npm/covcom/                package.json, bin/covcom (node shim),
 *                                   README.md, LICENSE
 *   dist/npm/cli-linux-x64/         package.json (os/cpu/libc), bin/covcom
 */

import { chmodSync, copyFileSync, existsSync, mkdirSync, rmSync } from 'node:fs';
import { join } from 'node:path';

export interface Target {
	suffix: string; // npm platform key: 'linux-x64-musl'
	bun: Bun.Build.CompileTarget; // bun compile target: 'bun-linux-x64-musl'
	os: string; // npm os field: 'linux'
	cpu: string; // npm cpu field: 'x64'
	libc?: 'glibc' | 'musl'; // npm libc field, linux only
	bin: string; // release binary filename: 'covcom-server-linux-x64-musl'
}

export interface StageOpts {
	metaName: string; // published meta package: 'covcom'
	scope: string; // platform package stem: 'cli' → '@covcom/cli-<suffix>'
	binName: string; // installed command name: 'covcom'
	summary: string; // one-line description for the meta manifest and README
	directory: string; // repository.directory for provenance: 'cli'
	distDir: string; // absolute path to the app's compiled binaries
	docker?: string; // docker hub URL, named in the shim's fallback message
	targets: Target[]; // full target table; the meta manifest lists all of it
	suffixes: string[]; // platform packages to stage in this run
}

const ROOT = join(import.meta.dir, '..');
const REPO = 'https://github.com/xero/covcom';

/** Resolve a list of requested suffixes ('all' expands) against a table. */
export function pickTargets(targets: Target[], suffixes: string[]): Target[] {
	if (suffixes.includes('all')) return targets;
	return suffixes.map((s) => {
		const t = targets.find((t) => t.suffix === s);
		if (!t) throw new Error(`unknown target: ${s} (known: ${targets.map((t) => t.suffix).join(', ')})`);
		return t;
	});
}

/** The suffix matching the running host, for default single-target staging. */
export function hostSuffix(targets: Target[]): string {
	const key = `${process.platform}-${process.arch}`;
	const t = targets.find((t) => t.suffix === key);
	if (!t) throw new Error(`host ${key} is not in the target table (${targets.map((t) => t.suffix).join(', ')})`);
	return t.suffix;
}

const pkgName = (scope: string, t: Target): string => `@covcom/${scope}-${t.suffix}`;
const binFile = (binName: string, t: Target): string => t.os === 'win32' ? `${binName}.exe` : binName;

function manifest(obj: object): string {
	return JSON.stringify(obj, null, '\t') + '\n';
}

// The shim is plain CJS, stdlib only; it runs under node (>=18) or bun. The
// three-stage failure story: unsupported platform lists the supported keys
// and points at the release and Docker channels, a missing platform package
// suggests a reinstall, and exec failures pass the binary's exit code
// through untouched.
function shim(o: StageOpts): string {
	const rows = o.targets
		.map((t) => `\t'${t.suffix}': ['${pkgName(o.scope, t)}', '${binFile(o.binName, t)}'],`)
		.join('\n');
	const fallback = [
		`process.stderr.write('Prebuilt binaries: ${REPO}/releases\\n');`,
		...(o.docker ? [`process.stderr.write('Docker image: ${o.docker}\\n');`] : []),
	].map((l) => '\t' + l).join('\n');
	return `#!/usr/bin/env node
// AUTO-GENERATED by scripts/npm.ts. Do not edit.
'use strict';

const { execFileSync } = require('child_process');
const { join } = require('path');

const PLATFORMS = {
${rows}
};

// Bun compiles separate glibc and musl linux binaries, so linux keys carry a
// libc suffix. glibcVersionRuntime is absent from process.report under musl.
function libcSuffix() {
	try {
		return process.report.getReport().header.glibcVersionRuntime ? '' : '-musl';
	} catch {
		return '';
	}
}

const key = process.platform === 'linux'
	? 'linux-' + process.arch + libcSuffix()
	: process.platform + '-' + process.arch;
const entry = PLATFORMS[key];

if (!entry) {
	process.stderr.write('${o.binName}: unsupported platform: ' + key + '\\n');
	process.stderr.write('Supported: ' + Object.keys(PLATFORMS).join(', ') + '\\n');
${fallback}
	process.exit(1);
}

const [pkg, bin] = entry;

let pkgJson;
try {
	pkgJson = require.resolve(pkg + '/package.json');
} catch {
	process.stderr.write('${o.binName}: platform package ' + pkg + ' is not installed.\\n');
	process.stderr.write('Try reinstalling: npm install -g ${o.metaName}\\n');
	process.exit(1);
}

try {
	execFileSync(join(pkgJson, '..', 'bin', bin), process.argv.slice(2), { stdio: 'inherit' });
} catch (e) {
	process.exit(e.status ?? 1);
}
`;
}

function readme(o: StageOpts): string {
	const rows = o.targets
		.map((t) => `| ${t.suffix} | ${t.libc ?? '-'} | \`${pkgName(o.scope, t)}\` |`)
		.join('\n');
	return `# ${o.metaName}

> [!NOTE]
> ${o.summary}

---

## Install

\`\`\`sh
npm i -g ${o.metaName}
\`\`\`

\`bunx ${o.metaName}\` works too. Each platform package carries a prebuilt
binary with its runtime embedded, so installing from npm does not require
Bun. The launcher shim runs on Node 18 or newer, or on Bun.

## Supported platforms

| platform | libc | package |
|----------|------|---------|
${rows}

Other platforms can use the [prebuilt release binaries](${REPO}/releases)${o.docker ? ` or the [Docker image](${o.docker})` : ''}.

## Links

- [Repository](${REPO})
- [Usage guide](${REPO}/blob/main/docs/USAGE.md)
- [Security policy](${REPO}/blob/main/SECURITY.md)
`;
}

/** Stage the meta package and the requested platform packages. */
export async function stageNpm(o: StageOpts): Promise<void> {
	const root = JSON.parse(await Bun.file(join(ROOT, 'package.json')).text());
	const version: string = root.version;
	const outRoot = join(ROOT, 'dist', 'npm');
	const repository = (directory: string): object => ({
		type: 'git',
		url: `git+${REPO}.git`,
		directory,
	});

	for (const t of pickTargets(o.targets, o.suffixes)) {
		const src = join(o.distDir, t.bin);
		if (!existsSync(src)) {
			throw new Error(`${src} missing; run the binary build for ${t.suffix} first`);
		}
		const dir = join(outRoot, `${o.scope}-${t.suffix}`);
		rmSync(dir, { recursive: true, force: true });
		mkdirSync(join(dir, 'bin'), { recursive: true });
		await Bun.write(join(dir, 'package.json'), manifest({
			name: pkgName(o.scope, t),
			version,
			description: `${o.metaName} ${t.suffix}${t.libc ? ` (${t.libc})` : ''} binary`,
			license: root.license,
			repository: repository(o.directory),
			os: [t.os],
			cpu: [t.cpu],
			...(t.libc ? { libc: [t.libc] } : {}),
			files: ['bin/'],
			publishConfig: { access: 'public', provenance: true },
		}));
		const staged = join(dir, 'bin', binFile(o.binName, t));
		copyFileSync(src, staged);
		chmodSync(staged, 0o755);
		copyFileSync(join(ROOT, 'LICENSE'), join(dir, 'LICENSE'));
		process.stdout.write(`Staged ${dir}\n`);
	}

	const meta = join(outRoot, o.metaName);
	rmSync(meta, { recursive: true, force: true });
	mkdirSync(join(meta, 'bin'), { recursive: true });
	await Bun.write(join(meta, 'package.json'), manifest({
		name: o.metaName,
		version,
		description: o.summary,
		license: root.license,
		author: root.author,
		repository: repository(o.directory),
		homepage: `${REPO}#readme`,
		bin: { [o.binName]: `bin/${o.binName}` },
		files: ['bin/'],
		engines: { node: '>=18' },
		optionalDependencies: Object.fromEntries(
			o.targets.map((t) => [pkgName(o.scope, t), version]),
		),
		publishConfig: { access: 'public', provenance: true },
		keywords: root.keywords,
	}));
	const shimPath = join(meta, 'bin', o.binName);
	await Bun.write(shimPath, shim(o));
	chmodSync(shimPath, 0o755);
	await Bun.write(join(meta, 'README.md'), readme(o));
	copyFileSync(join(ROOT, 'LICENSE'), join(meta, 'LICENSE'));
	process.stdout.write(`Staged ${meta}\n`);
}
