/**
 * version.ts - shared version codegen for every app build.
 *
 * Bakes the version facts in at build time so each app carries constants with
 * no runtime package.json read. VERSION comes from the project root
 * package.json; PROTOCOL_HEX is the wire version the lib already renders.
 * Callers pass an absolute out-path anchored to their own import.meta.dir.
 */

import { join } from 'node:path';
import { PROTOCOL } from '../lib/src/protocol.ts';

const ROOT = join(import.meta.dir, '..');

export async function bundleVersion(out: string): Promise<void> {
	process.stdout.write('Bundling version...\n');
	const pkg = await Bun.file(join(ROOT, 'package.json')).json();
	await Bun.write(out,
		'// AUTO-GENERATED by build.ts. Do not edit.\n' +
		`export const VERSION = ${JSON.stringify(pkg.version)};\n` +
		`export const PROTOCOL_HEX = ${JSON.stringify(PROTOCOL.protocolVersionHex)};\n`,
	);
	process.stdout.write(`  → ${out}\n`);
}
