/**
 * XChaCha20Cipher with a filesystem-backed pool worker.
 *
 * Compiled Bun binaries (`bun build --compile`) resolve `new Worker(url)`
 * through the embedded module map. Blob URLs aren't embedded modules, so the
 * worker fails with `MODULE_NOT_FOUND: Module not found 'blob:…'`. Spawning
 * from `new URL('./pool-worker.js', import.meta.url)` also can't be made to
 * work because the worker source lives in `node_modules` and isn't part of
 * the CLI's static module graph.
 *
 * Workaround: write the bundled worker source (an IIFE built with
 * `format: 'iife'`, generated by `build.ts`) to a temp file once at module
 * load, then spawn each worker from that real filesystem path. Bun's Worker
 * constructor accepts absolute paths and reads them at runtime. The temp dir
 * is cleaned up on process exit; OS tempdir reaping covers anomalous exits.
 */
import { mkdtempSync, rmSync, writeFileSync } from 'fs';
import { tmpdir }                             from 'os';
import { join }                               from 'path';
import { XChaCha20Cipher }                    from 'leviathan-crypto';
import type { CipherSuite }                   from 'leviathan-crypto';
import { WORKER_BUNDLE as CHACHA_BUNDLE }     from './chacha/worker-bundle.js';

const WORKER_DIR  = mkdtempSync(join(tmpdir(), 'covcom-worker-'));
const WORKER_PATH = join(WORKER_DIR, 'chacha-pool-worker.js');
writeFileSync(WORKER_PATH, CHACHA_BUNDLE);

process.on('exit', () => {
	try {
		rmSync(WORKER_DIR, { recursive: true, force: true });
	} catch { /* best effort */ }
});

export const XChaCha20CipherBun: CipherSuite = {
	...XChaCha20Cipher,
	createPoolWorker(): Worker {
		return new Worker(WORKER_PATH, { type: 'classic' });
	},
};
